//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTwitterCloneApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Following
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public int FollowingUser_ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
